FROM golang:1.24-alpine3.21 AS builder

WORKDIR /app

RUN go install github.com/air-verse/air@latest

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY ./internal ./internal
COPY ./main.go ./
COPY ./.air.toml ./

CMD ["air", "-c", ".air.toml"]
