// This file is auto-generated by @hey-api/openapi-ts

export type GetApiV1VolumesData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/api/v1/volumes";
};

export type GetApiV1VolumesResponses = {
	/**
	 * A list of volumes
	 */
	200: {
		volumes: Array<{
			createdAt: string;
			mountpoint: string;
			name: string;
		}>;
	};
};

export type GetApiV1VolumesResponse =
	GetApiV1VolumesResponses[keyof GetApiV1VolumesResponses];

export type ClientOptions = {
	baseUrl: "http://localhost:3000" | (string & {});
};
