// This file is auto-generated by @hey-api/openapi-ts

export type ListVolumesData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/api/v1/volumes";
};

export type ListVolumesResponses = {
	/**
	 * A list of volumes
	 */
	200: {
		volumes: Array<{
			autoRemount: 0 | 1;
			config:
				| {
						backend: "directory";
				  }
				| {
						backend: "nfs";
						exportPath: string;
						server: string;
						version: "3" | "4" | "4.1";
						port?: number | string;
				  }
				| {
						backend: "smb";
				  };
			createdAt: number;
			lastError: string;
			lastHealthCheck: number;
			name: string;
			path: string;
			status: "error" | "mounted" | "unknown" | "unmounted";
			type: "directory" | "nfs" | "smb";
			updatedAt: number;
		}>;
	};
};

export type ListVolumesResponse = ListVolumesResponses[keyof ListVolumesResponses];

export type CreateVolumeData = {
	body?: {
		config:
			| {
					backend: "directory";
			  }
			| {
					backend: "nfs";
					exportPath: string;
					server: string;
					version: "3" | "4" | "4.1";
					port?: number | string;
			  }
			| {
					backend: "smb";
			  };
		name: string;
	};
	path?: never;
	query?: never;
	url: "/api/v1/volumes";
};

export type CreateVolumeResponses = {
	/**
	 * Volume created successfully
	 */
	201: {
		message: string;
		volume: {
			name: string;
			path: string;
		};
	};
};

export type CreateVolumeResponse = CreateVolumeResponses[keyof CreateVolumeResponses];

export type TestConnectionData = {
	body?: {
		config:
			| {
					backend: "directory";
			  }
			| {
					backend: "nfs";
					exportPath: string;
					server: string;
					version: "3" | "4" | "4.1";
					port?: number | string;
			  }
			| {
					backend: "smb";
			  };
	};
	path?: never;
	query?: never;
	url: "/api/v1/volumes/test-connection";
};

export type TestConnectionResponses = {
	/**
	 * Connection test result
	 */
	200: {
		message: string;
		success: boolean;
	};
};

export type TestConnectionResponse = TestConnectionResponses[keyof TestConnectionResponses];

export type DeleteVolumeData = {
	body?: never;
	path: {
		name: string;
	};
	query?: never;
	url: "/api/v1/volumes/{name}";
};

export type DeleteVolumeResponses = {
	/**
	 * Volume deleted successfully
	 */
	200: {
		message: string;
	};
};

export type DeleteVolumeResponse = DeleteVolumeResponses[keyof DeleteVolumeResponses];

export type GetVolumeData = {
	body?: never;
	path: {
		name: string;
	};
	query?: never;
	url: "/api/v1/volumes/{name}";
};

export type GetVolumeErrors = {
	/**
	 * Volume not found
	 */
	404: unknown;
};

export type GetVolumeResponses = {
	/**
	 * Volume details
	 */
	200: {
		statfs: {
			free: number;
			total: number;
			used: number;
		};
		volume: {
			autoRemount: 0 | 1;
			config:
				| {
						backend: "directory";
				  }
				| {
						backend: "nfs";
						exportPath: string;
						server: string;
						version: "3" | "4" | "4.1";
						port?: number | string;
				  }
				| {
						backend: "smb";
				  };
			createdAt: number;
			lastError: string;
			lastHealthCheck: number;
			name: string;
			path: string;
			status: "error" | "mounted" | "unknown" | "unmounted";
			type: "directory" | "nfs" | "smb";
			updatedAt: number;
		};
	};
};

export type GetVolumeResponse = GetVolumeResponses[keyof GetVolumeResponses];

export type UpdateVolumeData = {
	body?: {
		config:
			| {
					backend: "directory";
			  }
			| {
					backend: "nfs";
					exportPath: string;
					server: string;
					version: "3" | "4" | "4.1";
					port?: number | string;
			  }
			| {
					backend: "smb";
			  };
	};
	path: {
		name: string;
	};
	query?: never;
	url: "/api/v1/volumes/{name}";
};

export type UpdateVolumeErrors = {
	/**
	 * Volume not found
	 */
	404: unknown;
};

export type UpdateVolumeResponses = {
	/**
	 * Volume updated successfully
	 */
	200: {
		message: string;
		volume: {
			config:
				| {
						backend: "directory";
				  }
				| {
						backend: "nfs";
						exportPath: string;
						server: string;
						version: "3" | "4" | "4.1";
						port?: number | string;
				  }
				| {
						backend: "smb";
				  };
			createdAt: number;
			name: string;
			path: string;
			type: string;
			updatedAt: number;
		};
	};
};

export type UpdateVolumeResponse = UpdateVolumeResponses[keyof UpdateVolumeResponses];

export type MountVolumeData = {
	body?: never;
	path: {
		name: string;
	};
	query?: never;
	url: "/api/v1/volumes/{name}/mount";
};

export type MountVolumeErrors = {
	/**
	 * Volume not found
	 */
	404: unknown;
};

export type MountVolumeResponses = {
	/**
	 * Volume mounted successfully
	 */
	200: {
		status: "error" | "mounted" | "unmounted";
		error?: string;
	};
};

export type MountVolumeResponse = MountVolumeResponses[keyof MountVolumeResponses];

export type UnmountVolumeData = {
	body?: never;
	path: {
		name: string;
	};
	query?: never;
	url: "/api/v1/volumes/{name}/unmount";
};

export type UnmountVolumeErrors = {
	/**
	 * Volume not found
	 */
	404: unknown;
};

export type UnmountVolumeResponses = {
	/**
	 * Volume unmounted successfully
	 */
	200: {
		status: "error" | "mounted" | "unmounted";
		error?: string;
	};
};

export type UnmountVolumeResponse = UnmountVolumeResponses[keyof UnmountVolumeResponses];

export type ClientOptions = {
	baseUrl: "http://localhost:3000" | (string & {});
};
